name: language
version: 0.0.1
author: Karan Goel <karan@goel.io>
description: Nothing to see here right now.
homepage: https://github.com/karan/language.dart
documentation: https://github.com/karan/language.dart
